package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// newGenWorkflowCmd returns a command that generates a GitHub Actions workflow
// file that automatically runs ai-mr-comment on every pull request.
func newGenWorkflowCmd() *cobra.Command {
	var provider, outputPath string
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "gen-workflow",
		Short: "Generate a GitHub Actions workflow for automatic AI PR review",
		Long: `Writes a GitHub Actions workflow YAML file that automatically runs
ai-mr-comment on every pull request (opened, synchronised, reopened) and
posts the AI review as a PR comment.

Use --output=- to print to stdout instead of writing a file.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			secretName, ok := providerSecrets[provider]
			if !ok {
				supported := []string{"openai", "anthropic", "gemini"}
				return fmt.Errorf("unsupported provider %q for gen-workflow; supported: %s", provider, strings.Join(supported, ", "))
			}
			providerEnvVar := secretName // env var name == secret name

			workflow := fmt.Sprintf(`name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Install ai-mr-comment
        run: |
          curl -fsSL https://github.com/pbsladek/ai-mr-comment/releases/latest/download/ai-mr-comment-linux-amd64 \
            -o /usr/local/bin/ai-mr-comment
          chmod +x /usr/local/bin/ai-mr-comment

      - name: Generate and post AI review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          %s: ${{ secrets.%s }}
        run: |
          ai-mr-comment \
            --pr "${{ github.event.pull_request.html_url }}" \
            --provider %s \
            --post
`, providerEnvVar, secretName, provider)

			if outputPath == "-" {
				_, _ = fmt.Fprint(cmd.OutOrStdout(), workflow)
				return nil
			}

			if dryRun {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Dry run: would write workflow to %s using provider %s and secret %s\n", outputPath, provider, secretName)
				return nil
			}

			if err := os.MkdirAll(filepath.Dir(outputPath), 0o750); err != nil {
				return fmt.Errorf("creating output directory: %w", err)
			}
			if err := os.WriteFile(outputPath, []byte(workflow), 0o600); err != nil {
				return fmt.Errorf("writing workflow file: %w", err)
			}
			_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "Wrote workflow to %s\n", outputPath)
			_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "Add secret %q to your repo, then commit the workflow file.\n", secretName)
			return nil
		},
	}

	cmd.Flags().StringVar(&provider, "provider", "openai", "AI provider to use in the workflow (openai, anthropic, gemini)")
	cmd.Flags().StringVar(&outputPath, "output", ".github/workflows/ai-review.yml", "Output file path (use - for stdout)")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print what would be written without creating files")
	_ = cmd.RegisterFlagCompletionFunc("provider", completeValues([]string{"openai", "anthropic", "gemini"}))
	return cmd
}

// aliasBlock is the shell snippet printed by gen-aliases.
// It is a Go constant so tests can verify the exact output.
const aliasBlock = `# ai-mr-comment v1 aliases
# Generated by: ai-mr-comment gen-aliases
# Add to your ~/.bashrc or ~/.zshrc, then reload with: source ~/.bashrc

alias amc='ai-mr-comment'                                      # main command
alias amc-staged='ai-mr-comment --staged'                      # review staged changes
alias amc-commit='ai-mr-comment --commit-msg --staged'         # generate commit message
alias amc-commit-multi='ai-mr-comment --commit-msg --multi-line --staged'  # multi-line commit (pre-fills PR/MR)
alias amc-title='ai-mr-comment --title'                        # include a PR/MR title
alias amc-json='ai-mr-comment --format=json'                   # JSON output
alias amc-debug='ai-mr-comment --debug'                        # token/cost estimate
alias amc-chaos='ai-mr-comment --chaos'                        # chaotic but accurate MR/PR description
alias amc-haiku='ai-mr-comment --haiku'                        # MR/PR description as haikus
alias amc-roast='ai-mr-comment --roast'                        # sardonically judgmental MR/PR description
alias amc-intern='ai-mr-comment --intern'                      # overly enthusiastic junior-dev MR/PR description
alias amc-shakespeare='ai-mr-comment --shakespeare'            # MR/PR description in Shakespearean English
alias amc-manager='ai-mr-comment --manager'                    # passive-aggressive corporate MR/PR description
alias amc-yoda='ai-mr-comment --yoda'                          # MR/PR description in Yoda syntax
alias amc-excuse='ai-mr-comment --excuse'                      # technically accurate MR/PR description with excuses
alias amc-conventional='ai-mr-comment --template=conventional' # conventional commits style MR/PR description
alias amc-emoji='ai-mr-comment --template=emoji'               # emoji-rich MR/PR description
alias amc-jira='ai-mr-comment --template=jira'                 # Jira-friendly MR/PR description
alias amc-monday='ai-mr-comment --template=monday'             # Monday.com task-style MR/PR description
alias amc-sassy='ai-mr-comment --template=sassy'               # sassy MR/PR description
alias amc-technical='ai-mr-comment --template=technical'       # deeply technical MR/PR description
alias amc-user='ai-mr-comment --template=user-focused'         # user-impact focused MR/PR description
alias amc-qc='ai-mr-comment quick-commit'                      # stage + AI commit + push
alias amc-qc-dry='ai-mr-comment quick-commit --dry-run'        # preview commit msg
alias amc-qc-edit='ai-mr-comment quick-commit --edit'          # edit generated commit msg before committing
alias amc-qc-local='ai-mr-comment quick-commit --no-push'      # commit locally without pushing
alias amc-qc-tracked='ai-mr-comment quick-commit --tracked-only'  # commit tracked changes only
alias amc-qc-signoff='ai-mr-comment quick-commit --signoff'    # append Signed-off-by trailer
alias amc-qc-fix='ai-mr-comment quick-commit --type=fix'       # force fix commit type
alias amc-qc-docs='ai-mr-comment quick-commit --type=docs'     # force docs commit type
alias amc-qc-detailed='ai-mr-comment quick-commit --message-template=detailed'  # detailed commit body
alias amc-qc-release='ai-mr-comment quick-commit --message-template=release'    # release-note-ready commit body
alias amc-qc-ticket='ai-mr-comment quick-commit --message-template=ticket'       # ticket-oriented commit body
alias amc-qc-breaking='ai-mr-comment quick-commit --breaking'  # breaking change commit (feat!)
alias amc-qc-chaos='ai-mr-comment quick-commit --chaos'              # funny/absurd conventional commit
alias amc-qc-haiku='ai-mr-comment quick-commit --haiku'              # commit description as a haiku
alias amc-qc-roast='ai-mr-comment quick-commit --roast'              # passive-aggressive accurate commit
alias amc-qc-fortune='ai-mr-comment quick-commit --fortune'          # commit + dev-wisdom fortune trailer
alias amc-qc-monday='ai-mr-comment quick-commit --monday'            # low-energy Monday-morning commit
alias amc-qc-jira='ai-mr-comment quick-commit --jira'                # commit prefixed with Jira ticket key
alias amc-qc-emoji='ai-mr-comment quick-commit --emoji-commit'       # commit with type-matched gitmoji
alias amc-qc-sassy='ai-mr-comment quick-commit --sassy'              # sassy but accurate commit
alias amc-qc-technical='ai-mr-comment quick-commit --technical'      # maximum technical precision commit
alias amc-qc-intern='ai-mr-comment quick-commit --intern'            # overly enthusiastic junior-dev commit
alias amc-qc-shakespeare='ai-mr-comment quick-commit --shakespeare'  # commit description in Shakespearean English
alias amc-qc-manager='ai-mr-comment quick-commit --manager'          # passive-aggressive corporate commit
alias amc-qc-yoda='ai-mr-comment quick-commit --yoda'                # commit description in Yoda syntax
alias amc-qc-excuse='ai-mr-comment quick-commit --excuse'            # accurate commit with built-in excuse
alias amc-cl='ai-mr-comment changelog'                         # generate changelog entry
alias amc-models='ai-mr-comment models'                        # list available models
alias amc-init='ai-mr-comment init-config'                     # write default config
`

// newGenAliasesCmd returns the gen-aliases subcommand, which prints a shell
// alias block for ai-mr-comment to stdout. Users source the output into their
// shell profile to get short amc-* aliases.
func newGenAliasesCmd() *cobra.Command {
	var shell, outputPath string

	cmd := &cobra.Command{
		Use:   "gen-aliases",
		Short: "Print shell aliases for ai-mr-comment (amc and amc-*)",
		Long: `Prints a block of shell alias definitions to stdout.

Add them to your shell profile with one of:

  # Append once:
  ai-mr-comment gen-aliases >> ~/.bashrc   # or ~/.zshrc

  # Re-generate on every shell start (always up-to-date):
  eval "$(ai-mr-comment gen-aliases)"

Aliases defined:
  amc                — shorthand for ai-mr-comment
  amc-staged         — review staged changes
  amc-commit         — generate a commit message (--commit-msg --staged)
  amc-commit-multi   — multi-line commit message that pre-fills PR/MR title+description
  amc-title          — generate comment + PR/MR title
  amc-json           — output as JSON
  amc-debug          — show token/cost estimate
  amc-chaos          — chaotic but accurate MR/PR description
  amc-haiku          — MR/PR description as haikus
  amc-roast          — sardonically judgmental MR/PR description
  amc-intern         — overly enthusiastic junior-dev MR/PR description
  amc-shakespeare    — MR/PR description in Shakespearean English
  amc-manager        — passive-aggressive corporate MR/PR description
  amc-yoda           — MR/PR description in Yoda syntax
  amc-excuse         — technically accurate MR/PR description with excuses
  amc-conventional   — conventional commits style MR/PR description
  amc-emoji          — emoji-rich MR/PR description
  amc-jira           — Jira-friendly MR/PR description
  amc-monday         — Monday.com task-style MR/PR description
  amc-sassy          — sassy MR/PR description
  amc-technical      — deeply technical MR/PR description
  amc-user           — user-impact focused MR/PR description
  amc-qc             — quick-commit (stage + AI commit + push)
  amc-qc-dry         — quick-commit dry-run (preview only)
  amc-qc-edit        — quick-commit with editor review before commit
  amc-qc-local       — quick-commit without pushing
  amc-qc-tracked     — quick-commit tracked changes only
  amc-qc-signoff     — quick-commit with Signed-off-by trailer
  amc-qc-fix         — quick-commit forcing fix type
  amc-qc-docs        — quick-commit forcing docs type
  amc-qc-detailed    — quick-commit with detailed message template
  amc-qc-release     — quick-commit with release-note-ready message template
  amc-qc-ticket      — quick-commit with ticket-oriented message template
  amc-qc-breaking    — quick-commit with breaking change (feat!)
  amc-qc-chaos       — quick-commit with funny/absurd conventional commit
  amc-qc-haiku       — quick-commit with commit description as a haiku
  amc-qc-roast       — quick-commit with passive-aggressive accurate commit
  amc-qc-fortune     — quick-commit with dev-wisdom fortune trailer
  amc-qc-monday      — quick-commit with casual Monday-morning tone
  amc-qc-jira        — quick-commit prefixed with Jira ticket key from branch
  amc-qc-emoji       — quick-commit with type-matched gitmoji appended
  amc-qc-sassy       — quick-commit with sassy but accurate message
  amc-qc-technical   — quick-commit with maximum technical precision
  amc-qc-intern      — quick-commit as an overly enthusiastic junior dev
  amc-qc-shakespeare — quick-commit description in Shakespearean English
  amc-qc-manager     — quick-commit in passive-aggressive corporate speak
  amc-qc-yoda        — quick-commit description in Yoda syntax
  amc-qc-excuse      — quick-commit with a built-in excuse
  amc-cl             — changelog subcommand
  amc-models         — list available models
  amc-init           — write default config file`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if shell != "bash" && shell != "zsh" {
				return fmt.Errorf("unsupported shell %q: must be bash or zsh", shell)
			}

			out := cmd.OutOrStdout()
			_, _ = fmt.Fprint(out, aliasBlock)

			if outputPath != "" {
				return os.WriteFile(outputPath, []byte(aliasBlock), 0600) //nolint:gosec // G306: user-owned shell config file
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&shell, "shell", "bash", "Target shell: bash or zsh (both use the same alias syntax)")
	cmd.Flags().StringVar(&outputPath, "output", "", "Also write aliases to this file (e.g. ~/.bashrc)")
	_ = cmd.RegisterFlagCompletionFunc("shell", completeValues([]string{"bash", "zsh"}))
	return cmd
}
